from .serializers_head_clima import *
from .serializers_onoff_boarding import *
from .serializers_nucleo import *
from .serializers_sanciones import *
from .serializers_descriptor_perfil import *
from .serializers_easyaudit import *
from .serializers_seleccion_contratacion import *
from .serializers_capacitacion import *
from .serializers_evaluacion import *
