"""
Django settings for AURORA project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/
"""
"""
Django settings for AURORA project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os

from pathlib import Path
# ambiente_sap = '172.10.0.6' #calidad
# sap_user ='INTERFACESAP'
# sap_pass='1nt3rf4c3sF4r!n73r'


SAP = {
      'ambiente_sap': '172.10.0.6',
      'sap_user': 'INTERFACESAP',
      'sap_pass': '1nt3rf4c3sF4r!n73r',
}
#ambiente_sap = '172.10.0.2' #prd

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p@p%vdh2$t12(pvmp-s-6yb(jcf5lwga2m2e_6g_p+3mqw7%)b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['172.16.2.206','localhost','127.0.0.1','172.16.2.218','172.16.2.223']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'HEADCOUNT.apps.HeadcountConfig',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_crontab',
    'easyaudit',


]
DJANGO_EASY_AUDIT_WATCH_MODEL_EVENTS = True

DJANGO_EASY_AUDIT_WATCH_AUTH_EVENTS= True

DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS= True

DJANGO_EASY_AUDIT_LOGGING_BACKEND='AURORA.easyaudit.backend_easyaudit.ModelBackend'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware'
     
    
    
]

ROOT_URLCONF = 'AURORA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'AURORA.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# DATABASES = {

#     'default': {

#         'ENGINE': 'django.db.backends.postgresql_psycopg2',

#         'NAME': 'aurora',

#         'USER': 'postgres',

#         'PASSWORD': 'Pmolina00*',

#         'HOST': 'localhost',
#     }

#}
# }
# DATABASES = {
#   'default': {
#       'ENGINE': 'django.db.backends.postgresql_psycopg2',
#       'NAME': 'AURORA',
#       'USER': 'desarrollo',
#       'PASSWORD': '1nfr42018',
#       'HOST': '172.16.2.153',
#       'PORT': '',
#   }
# }

DATABASES = {
  'default': {
      'ENGINE': 'django.db.backends.postgresql_psycopg2',
      'NAME': 'AURORA',
      'USER': 'desarrollo',
      'PASSWORD': '1nfr42018',
      'HOST': '172.16.2.153',
      'PORT': '',
  }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'AURORA',
#         'USER': 'whernandez',
#         'PASSWORD': 'dev123',
#         'HOST': 'localhost',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

 
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/El_Salvador'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        
        
    ],
    'UPLOADED_FILES_USE_URL': False
}

CORS_ORIGIN_ALLOW_ALL = True
#CORS_ORIGIN_WHITELIST = (
#       'http://localhost:4200',
#)

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

MEDIA_ROOT=os.path.join(BASE_DIR,"media")
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.farinter.hn'
EMAIL_HOST_USER = 'aurora@farinter.hn'
EMAIL_HOST_PASSWORD = 'F4rinter#2021'
EMAIL_PORT = 25
EMAIL_USE_TLS = True

try:
    from .local_settings import *
except ImportError:
    pass

#esto es un comentario
CRONJOBS = [
    ('0 1 * * *', 'HEADCOUNT.cron.Formal_RFC_Carga_Masiva_Complementaria'),
    ('0 2 * * *', 'HEADCOUNT.cron.Funcional_RFC_Carga_Masiva_Complementaria'),
    ('0 4 * * *', 'HEADCOUNT.cron.Formal_RFC_Carga_Masiva'),
    ('0 5 * * *', 'HEADCOUNT.cron.Funcional_RFC_Carga_Masiva'),
    ('0 6 * * *', 'HEADCOUNT.cron.Formal_checklist'),
    ('0 6 * * *', 'HEADCOUNT.cron.Funcional_checklist'),
    ('0 6 * * *', 'HEADCOUNT.cron.Creacion_Usuario'),
    ('0 6 * * *', 'HEADCOUNT.cron.jefes_inmediatos'),
    ('0 6 * * *', 'HEADCOUNT.cron.informacin_powerBIviewsets'),
    ('0 6 * * *', 'HEADCOUNT.cron.Llenado_Encabezado'),
    ('0 6 * * *', 'HEADCOUNT.cron.cambio_estado_campanias'),
    ('0 6 * * *', 'HEADCOUNT.cron.cambio_estado_evento_capacitacion'),

    
    # ('0 6 * * *', 'HEADCOUNT.cron.Llenado_Encabezado'),

    


]